In [1]:
import keras
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential

In [2]:
df = pd.read_csv('/Users/srinathnarayanan/Downloads/Misc/DSD.csv')

In [3]:
df

,CustStorItemTriadID,BaseorderID,Createdate,RecDeliveryDate,CategoryID,OaMasterDistributorID,ConversionFactor,InventoryChange,ActualScans,ForecastedScans,...,ConversionUnits,MaxDeliveredQty,ConversionResidual,Previous2DelDate,MaxScanDate,MaxShipDate,TwoOrderAgo,QtyShippedTwoOrderAgo,Reviewed,IncInAnom
0,13761530,1867926,5/1/2020,5/7/2020,1,5,0.75,12,0,13,...,9,27,1,4/30/2020,4/29/2020,4/27/2020,9,0,1,1
1,13761530,1889852,5/7/2020,5/11/2020,1,5,0.75,3,0,18,...,9,27,6,5/4/2020,5/5/2020,5/4/2020,18,13,1,1
2,13761530,1899415,5/8/2020,5/14/2020,1,5,0.75,5,0,11,...,9,27,0,5/7/2020,5/6/2020,5/4/2020,9,0,1,1
3,13761530,1953002,5/21/2020,5/25/2020,1,5,0.75,5,0,16,...,9,27,0,5/18/2020,5/19/2020,5/18/2020,18,12,1,1
4,13761530,2048503,6/11/2020,6/15/2020,1,5,0.75,6,0,15,...,9,27,5,6/8/2020,6/9/2020,6/8/2020,18,9,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495597,21016901,2249563,7/24/2020,7/27/2020,1,5,0.75,1,0,3,...,4,8,2,7/20/2020,7/20/2020,7/20/2020,4,4,1,1
495598,21016901,2262011,7/28/2020,7/30/2020,1,5,0.75,4,0,3,...,4,8,0,7/23/2020,7/26/2020,7/20/2020,0,0,1,1
495599,21016901,2294886,8/4/2020,8/6/2020,1,5,0.75,5,0,5,...,4,8,1,7/30/2020,8/2/2020,7/30/2020,0,4,1,1
495600,21016901,2319043,8/7/2020,8/10/2020,1,5,0.75,7,0,3,...,4,8,0,8/3/2020,8/4/2020,7/30/2020,8,0,1,1
495601,21016901,2373971,8/14/2020,8/17/2020,1,5,0.75,0,0,0,...,4,8,0,8/10/2020,8/7/2020,8/10/2020,4,4,1,1

In [4]:
df = df.fillna(0)

In [5]:
df.isnull().values.any()

False

In [6]:
df.isna().sum()

CustStorItemTriadID      0
BaseorderID              0
Createdate               0
RecDeliveryDate          0
CategoryID               0
OaMasterDistributorID    0
ConversionFactor         0
InventoryChange          0
ActualScans              0
ForecastedScans          0
ModelUsed                0
WeightData               0
BaseOrder                0
SlowMoving               0
TooBig                   0
TrueUpAdjQty             0
TUAIssue                 0
OriginalPropOrderQty     0
PropOrderQty             0
ConversionUnits          0
MaxDeliveredQty          0
ConversionResidual       0
Previous2DelDate         0
MaxScanDate              0
MaxShipDate              0
TwoOrderAgo              0
QtyShippedTwoOrderAgo    0
Reviewed                 0
IncInAnom                0
dtype: int64

In [7]:
X = df.drop(['CustStorItemTriadID','BaseorderID','ConversionFactor','ModelUsed','TUAIssue','ConversionUnits','IncInAnom','Createdate','RecDeliveryDate','Previous2DelDate','MaxScanDate','MaxShipDate'], axis = 1)
Y = df['PropOrderQty']

In [8]:
X

,CategoryID,OaMasterDistributorID,InventoryChange,ActualScans,ForecastedScans,WeightData,BaseOrder,SlowMoving,TooBig,TrueUpAdjQty,OriginalPropOrderQty,PropOrderQty,MaxDeliveredQty,ConversionResidual,TwoOrderAgo,QtyShippedTwoOrderAgo,Reviewed
0,1,5,12,0,13,1,8,0,0,0,9,9,27,1,9,0,1
1,1,5,3,0,18,1,26,0,0,-9,18,18,27,6,18,13,1
2,1,5,5,0,11,1,10,0,0,-2,9,9,27,0,9,0,1
3,1,5,5,0,16,1,14,0,0,-6,9,9,27,0,18,12,1
4,1,5,6,0,15,1,22,0,0,-5,18,18,27,5,18,9,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495597,1,5,1,0,3,0,5,0,0,-1,4,4,8,2,4,4,1
495598,1,5,4,0,3,0,0,0,0,0,0,0,8,0,0,0,1
495599,1,5,5,0,5,4,6,0,1,2,12,8,8,1,0,4,1
495600,1,5,7,0,3,4,3,0,0,-3,4,4,8,0,8,0,1
495601,1,5,0,0,0,0,0,0,0,-2,0,-2,8,0,4,4,1

In [9]:
model = keras.sequential()

model.add(keras.layers.dense(16,activation = relu,input_shape = (8,)))
model.add(keras.layers.dense(16,activation = relu))
model.add(keras.layers.dense(1))

model.compile(optimizer = 'adam',loss = 'mean_squared_error')

AttributeError: module 'keras' has no attribute 'sequential'