In [1]:
#Import Libraries

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

In [3]:
#Reading the data and viewing

In [4]:
df = pd.read_csv('/Users/srinathnarayanan/Downloads/Misc/DSD.csv',header = 0,index_col = False)

In [5]:
df

,CustStorItemTriadID,BaseorderID,Createdate,RecDeliveryDate,CategoryID,OaMasterDistributorID,ConversionFactor,InventoryChange,ActualScans,ForecastedScans,...,ConversionUnits,MaxDeliveredQty,ConversionResidual,Previous2DelDate,MaxScanDate,MaxShipDate,TwoOrderAgo,QtyShippedTwoOrderAgo,Reviewed,IncInAnom
0,13761530,1867926,5/1/2020,5/7/2020,1,5,0.75,12,0,13,...,9,27,1,4/30/2020,4/29/2020,4/27/2020,9,0,1,1
1,13761530,1889852,5/7/2020,5/11/2020,1,5,0.75,3,0,18,...,9,27,6,5/4/2020,5/5/2020,5/4/2020,18,13,1,1
2,13761530,1899415,5/8/2020,5/14/2020,1,5,0.75,5,0,11,...,9,27,0,5/7/2020,5/6/2020,5/4/2020,9,0,1,1
3,13761530,1953002,5/21/2020,5/25/2020,1,5,0.75,5,0,16,...,9,27,0,5/18/2020,5/19/2020,5/18/2020,18,12,1,1
4,13761530,2048503,6/11/2020,6/15/2020,1,5,0.75,6,0,15,...,9,27,5,6/8/2020,6/9/2020,6/8/2020,18,9,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495597,21016901,2249563,7/24/2020,7/27/2020,1,5,0.75,1,0,3,...,4,8,2,7/20/2020,7/20/2020,7/20/2020,4,4,1,1
495598,21016901,2262011,7/28/2020,7/30/2020,1,5,0.75,4,0,3,...,4,8,0,7/23/2020,7/26/2020,7/20/2020,0,0,1,1
495599,21016901,2294886,8/4/2020,8/6/2020,1,5,0.75,5,0,5,...,4,8,1,7/30/2020,8/2/2020,7/30/2020,0,4,1,1
495600,21016901,2319043,8/7/2020,8/10/2020,1,5,0.75,7,0,3,...,4,8,0,8/3/2020,8/4/2020,7/30/2020,8,0,1,1
495601,21016901,2373971,8/14/2020,8/17/2020,1,5,0.75,0,0,0,...,4,8,0,8/10/2020,8/7/2020,8/10/2020,4,4,1,1

In [6]:
#Replacing Nan to zeros and make sure we dont delete any rows

In [7]:
df = df.fillna(0)

In [8]:
#Checking if Nan are replaced with zeros

In [9]:
df.isnull().values.any()

False

In [10]:
#Convert all dates to datetime

In [11]:
df[["Createdate", "RecDeliveryDate", "Previous2DelDate","MaxScanDate","MaxShipDate"]] = df[["Createdate", "RecDeliveryDate", "Previous2DelDate","MaxScanDate","MaxShipDate"]].apply(pd.to_datetime)

In [12]:
df

,CustStorItemTriadID,BaseorderID,Createdate,RecDeliveryDate,CategoryID,OaMasterDistributorID,ConversionFactor,InventoryChange,ActualScans,ForecastedScans,...,ConversionUnits,MaxDeliveredQty,ConversionResidual,Previous2DelDate,MaxScanDate,MaxShipDate,TwoOrderAgo,QtyShippedTwoOrderAgo,Reviewed,IncInAnom
0,13761530,1867926,2020-05-01,2020-05-07,1,5,0.75,12,0,13,...,9,27,1,2020-04-30,2020-04-29,2020-04-27,9,0,1,1
1,13761530,1889852,2020-05-07,2020-05-11,1,5,0.75,3,0,18,...,9,27,6,2020-05-04,2020-05-05,2020-05-04,18,13,1,1
2,13761530,1899415,2020-05-08,2020-05-14,1,5,0.75,5,0,11,...,9,27,0,2020-05-07,2020-05-06,2020-05-04,9,0,1,1
3,13761530,1953002,2020-05-21,2020-05-25,1,5,0.75,5,0,16,...,9,27,0,2020-05-18,2020-05-19,2020-05-18,18,12,1,1
4,13761530,2048503,2020-06-11,2020-06-15,1,5,0.75,6,0,15,...,9,27,5,2020-06-08,2020-06-09,2020-06-08,18,9,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495597,21016901,2249563,2020-07-24,2020-07-27,1,5,0.75,1,0,3,...,4,8,2,2020-07-20,2020-07-20,2020-07-20,4,4,1,1
495598,21016901,2262011,2020-07-28,2020-07-30,1,5,0.75,4,0,3,...,4,8,0,2020-07-23,2020-07-26,2020-07-20,0,0,1,1
495599,21016901,2294886,2020-08-04,2020-08-06,1,5,0.75,5,0,5,...,4,8,1,2020-07-30,2020-08-02,2020-07-30,0,4,1,1
495600,21016901,2319043,2020-08-07,2020-08-10,1,5,0.75,7,0,3,...,4,8,0,2020-08-03,2020-08-04,2020-07-30,8,0,1,1
495601,21016901,2373971,2020-08-14,2020-08-17,1,5,0.75,0,0,0,...,4,8,0,2020-08-10,2020-08-07,2020-08-10,4,4,1,1

In [13]:
# Function to assign value 0 if there is no match between OriginalPropOrderQty numbers with the sum(Actual+Forecasted+Weightdata)

In [14]:
df['Original'] = df['WeightData']+df['BaseOrder']+df['TrueUpAdjQty']

In [15]:
df

,CustStorItemTriadID,BaseorderID,Createdate,RecDeliveryDate,CategoryID,OaMasterDistributorID,ConversionFactor,InventoryChange,ActualScans,ForecastedScans,...,MaxDeliveredQty,ConversionResidual,Previous2DelDate,MaxScanDate,MaxShipDate,TwoOrderAgo,QtyShippedTwoOrderAgo,Reviewed,IncInAnom,Original
0,13761530,1867926,2020-05-01,2020-05-07,1,5,0.75,12,0,13,...,27,1,2020-04-30,2020-04-29,2020-04-27,9,0,1,1,9
1,13761530,1889852,2020-05-07,2020-05-11,1,5,0.75,3,0,18,...,27,6,2020-05-04,2020-05-05,2020-05-04,18,13,1,1,18
2,13761530,1899415,2020-05-08,2020-05-14,1,5,0.75,5,0,11,...,27,0,2020-05-07,2020-05-06,2020-05-04,9,0,1,1,9
3,13761530,1953002,2020-05-21,2020-05-25,1,5,0.75,5,0,16,...,27,0,2020-05-18,2020-05-19,2020-05-18,18,12,1,1,9
4,13761530,2048503,2020-06-11,2020-06-15,1,5,0.75,6,0,15,...,27,5,2020-06-08,2020-06-09,2020-06-08,18,9,1,1,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495597,21016901,2249563,2020-07-24,2020-07-27,1,5,0.75,1,0,3,...,8,2,2020-07-20,2020-07-20,2020-07-20,4,4,1,1,4
495598,21016901,2262011,2020-07-28,2020-07-30,1,5,0.75,4,0,3,...,8,0,2020-07-23,2020-07-26,2020-07-20,0,0,1,1,0
495599,21016901,2294886,2020-08-04,2020-08-06,1,5,0.75,5,0,5,...,8,1,2020-07-30,2020-08-02,2020-07-30,0,4,1,1,12
495600,21016901,2319043,2020-08-07,2020-08-10,1,5,0.75,7,0,3,...,8,0,2020-08-03,2020-08-04,2020-07-30,8,0,1,1,4
495601,21016901,2373971,2020-08-14,2020-08-17,1,5,0.75,0,0,0,...,8,0,2020-08-10,2020-08-07,2020-08-10,4,4,1,1,-2

In [16]:
def Original(df):
        if df['tooslow'] = 1
        if df['OriginalPropOrderQty'] == df['Original']:
            return 1
        return 0
df['Original'] = df.apply(Original, axis=1)

In [17]:
df

,CustStorItemTriadID,BaseorderID,Createdate,RecDeliveryDate,CategoryID,OaMasterDistributorID,ConversionFactor,InventoryChange,ActualScans,ForecastedScans,...,MaxDeliveredQty,ConversionResidual,Previous2DelDate,MaxScanDate,MaxShipDate,TwoOrderAgo,QtyShippedTwoOrderAgo,Reviewed,IncInAnom,Original
0,13761530,1867926,2020-05-01,2020-05-07,1,5,0.75,12,0,13,...,27,1,2020-04-30,2020-04-29,2020-04-27,9,0,1,1,1
1,13761530,1889852,2020-05-07,2020-05-11,1,5,0.75,3,0,18,...,27,6,2020-05-04,2020-05-05,2020-05-04,18,13,1,1,1
2,13761530,1899415,2020-05-08,2020-05-14,1,5,0.75,5,0,11,...,27,0,2020-05-07,2020-05-06,2020-05-04,9,0,1,1,1
3,13761530,1953002,2020-05-21,2020-05-25,1,5,0.75,5,0,16,...,27,0,2020-05-18,2020-05-19,2020-05-18,18,12,1,1,1
4,13761530,2048503,2020-06-11,2020-06-15,1,5,0.75,6,0,15,...,27,5,2020-06-08,2020-06-09,2020-06-08,18,9,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495597,21016901,2249563,2020-07-24,2020-07-27,1,5,0.75,1,0,3,...,8,2,2020-07-20,2020-07-20,2020-07-20,4,4,1,1,1
495598,21016901,2262011,2020-07-28,2020-07-30,1,5,0.75,4,0,3,...,8,0,2020-07-23,2020-07-26,2020-07-20,0,0,1,1,1
495599,21016901,2294886,2020-08-04,2020-08-06,1,5,0.75,5,0,5,...,8,1,2020-07-30,2020-08-02,2020-07-30,0,4,1,1,1
495600,21016901,2319043,2020-08-07,2020-08-10,1,5,0.75,7,0,3,...,8,0,2020-08-03,2020-08-04,2020-07-30,8,0,1,1,1
495601,21016901,2373971,2020-08-14,2020-08-17,1,5,0.75,0,0,0,...,8,0,2020-08-10,2020-08-07,2020-08-10,4,4,1,1,0

In [18]:
df.Original.value_counts()

1    406068
0     89534
Name: Original, dtype: int64

In [19]:
# Function to assign value 0 if there is no match between PropOrderQty and OriginalPropOrderQty

In [20]:
def target(df):
        if df['OriginalPropOrderQty'] == df['PropOrderQty']:
            return 1
        return 0
df['target'] = df.apply(target, axis=1)

In [21]:
df

,CustStorItemTriadID,BaseorderID,Createdate,RecDeliveryDate,CategoryID,OaMasterDistributorID,ConversionFactor,InventoryChange,ActualScans,ForecastedScans,...,ConversionResidual,Previous2DelDate,MaxScanDate,MaxShipDate,TwoOrderAgo,QtyShippedTwoOrderAgo,Reviewed,IncInAnom,Original,target
0,13761530,1867926,2020-05-01,2020-05-07,1,5,0.75,12,0,13,...,1,2020-04-30,2020-04-29,2020-04-27,9,0,1,1,1,1
1,13761530,1889852,2020-05-07,2020-05-11,1,5,0.75,3,0,18,...,6,2020-05-04,2020-05-05,2020-05-04,18,13,1,1,1,1
2,13761530,1899415,2020-05-08,2020-05-14,1,5,0.75,5,0,11,...,0,2020-05-07,2020-05-06,2020-05-04,9,0,1,1,1,1
3,13761530,1953002,2020-05-21,2020-05-25,1,5,0.75,5,0,16,...,0,2020-05-18,2020-05-19,2020-05-18,18,12,1,1,1,1
4,13761530,2048503,2020-06-11,2020-06-15,1,5,0.75,6,0,15,...,5,2020-06-08,2020-06-09,2020-06-08,18,9,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495597,21016901,2249563,2020-07-24,2020-07-27,1,5,0.75,1,0,3,...,2,2020-07-20,2020-07-20,2020-07-20,4,4,1,1,1,1
495598,21016901,2262011,2020-07-28,2020-07-30,1,5,0.75,4,0,3,...,0,2020-07-23,2020-07-26,2020-07-20,0,0,1,1,1,1
495599,21016901,2294886,2020-08-04,2020-08-06,1,5,0.75,5,0,5,...,1,2020-07-30,2020-08-02,2020-07-30,0,4,1,1,1,0
495600,21016901,2319043,2020-08-07,2020-08-10,1,5,0.75,7,0,3,...,0,2020-08-03,2020-08-04,2020-07-30,8,0,1,1,1,1
495601,21016901,2373971,2020-08-14,2020-08-17,1,5,0.75,0,0,0,...,0,2020-08-10,2020-08-07,2020-08-10,4,4,1,1,0,0

In [22]:
df.target.value_counts()

1    382184
0    113418
Name: target, dtype: int64

In [23]:
def targetsize(df):
        if df['MaxDeliveredQty'] == df['PropOrderQty']:
            return 1
        return 0
df['targetsize'] = df.apply(targetsize, axis=1)

In [24]:
df

,CustStorItemTriadID,BaseorderID,Createdate,RecDeliveryDate,CategoryID,OaMasterDistributorID,ConversionFactor,InventoryChange,ActualScans,ForecastedScans,...,Previous2DelDate,MaxScanDate,MaxShipDate,TwoOrderAgo,QtyShippedTwoOrderAgo,Reviewed,IncInAnom,Original,target,targetsize
0,13761530,1867926,2020-05-01,2020-05-07,1,5,0.75,12,0,13,...,2020-04-30,2020-04-29,2020-04-27,9,0,1,1,1,1,0
1,13761530,1889852,2020-05-07,2020-05-11,1,5,0.75,3,0,18,...,2020-05-04,2020-05-05,2020-05-04,18,13,1,1,1,1,0
2,13761530,1899415,2020-05-08,2020-05-14,1,5,0.75,5,0,11,...,2020-05-07,2020-05-06,2020-05-04,9,0,1,1,1,1,0
3,13761530,1953002,2020-05-21,2020-05-25,1,5,0.75,5,0,16,...,2020-05-18,2020-05-19,2020-05-18,18,12,1,1,1,1,0
4,13761530,2048503,2020-06-11,2020-06-15,1,5,0.75,6,0,15,...,2020-06-08,2020-06-09,2020-06-08,18,9,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495597,21016901,2249563,2020-07-24,2020-07-27,1,5,0.75,1,0,3,...,2020-07-20,2020-07-20,2020-07-20,4,4,1,1,1,1,0
495598,21016901,2262011,2020-07-28,2020-07-30,1,5,0.75,4,0,3,...,2020-07-23,2020-07-26,2020-07-20,0,0,1,1,1,1,0
495599,21016901,2294886,2020-08-04,2020-08-06,1,5,0.75,5,0,5,...,2020-07-30,2020-08-02,2020-07-30,0,4,1,1,1,0,1
495600,21016901,2319043,2020-08-07,2020-08-10,1,5,0.75,7,0,3,...,2020-08-03,2020-08-04,2020-07-30,8,0,1,1,1,1,0
495601,21016901,2373971,2020-08-14,2020-08-17,1,5,0.75,0,0,0,...,2020-08-10,2020-08-07,2020-08-10,4,4,1,1,0,0,0

In [25]:
df.targetsize.value_counts()

0    448096
1     47506
Name: targetsize, dtype: int64

In [26]:
features = df[['ConversionFactor','ConversionResidual','CategoryID','InventoryChange','ActualScans','ForecastedScans','WeightData','BaseOrder','BaseorderID','SlowMoving','TrueUpAdjQty','TooBig','ConversionUnits','targetsize','Original','TUAIssue','OriginalPropOrderQty','target']]
Labels = df[['targetsize']]

In [27]:
train_dataset = features.sample(frac=0.8, random_state=0)
test_dataset = (Labels.index)

In [28]:
def input_fn(features, Labels, training=True, batch_size=256):
    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices((dict(features), Labels))

    # Shuffle and repeat if you are in training mode.
    if training:
        dataset = dataset.shuffle(1000).repeat()
    
    return dataset.batch(batch_size)

In [29]:
# Feature columns describe how to use the input.
my_feature_columns = []
for key in features.keys():
    my_feature_columns.append(tf.feature_column.numeric_column(key=key))
print(my_feature_columns)

[NumericColumn(key='ConversionFactor', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='ConversionResidual', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='CategoryID', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='InventoryChange', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='ActualScans', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='ForecastedScans', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='WeightData', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='BaseOrder', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='BaseorderID', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='SlowMoving', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='TrueUpAdjQty', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='TooBig', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='ConversionUnits', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='targetsize', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='Original', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='TUAIssue', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='OriginalPropOrderQty', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='target', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [30]:
# Build a DNN with 2 hidden layers with 30 and 10 hidden nodes each.
classifier = tf.estimator.DNNClassifier(
    feature_columns=my_feature_columns,
    # Two hidden layers of 30 and 10 nodes respectively.
    hidden_units=[3, 10,0],
    # The model must choose between 3 classes.
    n_classes=3)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /var/folders/pt/1kfc9vl115q9sj4h8tff2q5c0000gn/T/tmpw1q7_ekt
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/pt/1kfc9vl115q9sj4h8tff2q5c0000gn/T/tmpw1q7_ekt', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

In [31]:
classifier.train(
    input_fn=lambda: input_fn(features,Labels,training=True),
    steps=5000)

WARNING:tensorflow:From /Users/srinathnarayanan/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From /Users/srinathnarayanan/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/adagrad.py:83: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/pt/1kfc9vl115q9sj4h8tff2q5c0000gn/T/tmpw1q7_ekt/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 1.0986121, step = 0
INFO:tensorflow:global_step/sec: 212.729
INFO:tensorflow:loss = 1.0986121, step = 100 (0.471 sec)
INFO:tensorflow:global_step/sec: 287.569
INFO:tensorflow:loss = 1.0986121, step = 200 (0.348 sec)
INFO:tensorflow:global_step/sec: 258.262
INFO:tensorflow:loss = 1.0986121, step = 300 (0.387 sec)
INFO:tensorflow:global_step/sec: 297.185
INFO:tensorflow:loss = 1.0986121, step = 400 (0.337 sec)
INFO:tensorflow:global_step/sec: 257.997
INFO:tensorflow:loss = 1.0986121, step = 500 (0.388 sec)
INFO:tensorflow:global_step/sec: 273.566
INFO:tensorflow:loss = 1.0986121, step = 600 (0.366 sec)
INFO:tensorflow:global_step/sec: 273.241
INFO:tensorflow:loss = 1.0986121, step = 700 (0.366 sec)
INFO:tensorflow:global_step/sec: 283.685
INFO:tensorflow:loss = 1.0986121, step = 800 (0.353 sec)
INFO:tensorflow:global_step/sec: 290.553
INFO:tensorflow:loss = 1.0986121, step = 900 (0.344 sec)
INFO:tensorflow:global_step/sec: 300.312
INFO:tensorflow:loss = 1.0986121, step = 1000 (0.333 sec)
INFO:tensorflow:global_step/sec: 265.976
INFO:tensorflow:loss = 1.0986121, step = 1100 (0.376 sec)
INFO:tensorflow:global_step/sec: 279.718
INFO:tensorflow:loss = 1.0986121, step = 1200 (0.357 sec)
INFO:tensorflow:global_step/sec: 277.304
INFO:tensorflow:loss = 1.0986121, step = 1300 (0.361 sec)
INFO:tensorflow:global_step/sec: 276.501
INFO:tensorflow:loss = 1.0986121, step = 1400 (0.362 sec)
INFO:tensorflow:global_step/sec: 285.152
INFO:tensorflow:loss = 1.0986121, step = 1500 (0.351 sec)
INFO:tensorflow:global_step/sec: 292.202
INFO:tensorflow:loss = 1.0986121, step = 1600 (0.342 sec)
INFO:tensorflow:global_step/sec: 271.18
INFO:tensorflow:loss = 1.0986121, step = 1700 (0.369 sec)
INFO:tensorflow:global_step/sec: 280.537
INFO:tensorflow:loss = 1.0986121, step = 1800 (0.356 sec)
INFO:tensorflow:global_step/sec: 290.437
INFO:tensorflow:loss = 1.0986121, step = 1900 (0.344 sec)
INFO:tensorflow:global_step/sec: 268.086
INFO:tensorflow:loss = 1.0986121, step = 2000 (0.373 sec)
INFO:tensorflow:global_step/sec: 260.808
INFO:tensorflow:loss = 1.0986121, step = 2100 (0.383 sec)
INFO:tensorflow:global_step/sec: 277.185
INFO:tensorflow:loss = 1.0986121, step = 2200 (0.361 sec)
INFO:tensorflow:global_step/sec: 274.452
INFO:tensorflow:loss = 1.0986121, step = 2300 (0.364 sec)
INFO:tensorflow:global_step/sec: 285.87
INFO:tensorflow:loss = 1.0986121, step = 2400 (0.350 sec)
INFO:tensorflow:global_step/sec: 252.234
INFO:tensorflow:loss = 1.0986121, step = 2500 (0.397 sec)
INFO:tensorflow:global_step/sec: 254.726
INFO:tensorflow:loss = 1.0986121, step = 2600 (0.393 sec)
INFO:tensorflow:global_step/sec: 270.923
INFO:tensorflow:loss = 1.0986121, step = 2700 (0.369 sec)
INFO:tensorflow:global_step/sec: 287.73
INFO:tensorflow:loss = 1.0986121, step = 2800 (0.348 sec)
INFO:tensorflow:global_step/sec: 254.66
INFO:tensorflow:loss = 1.0986121, step = 2900 (0.393 sec)
INFO:tensorflow:global_step/sec: 280.944
INFO:tensorflow:loss = 1.0986121, step = 3000 (0.356 sec)
INFO:tensorflow:global_step/sec: 261.757
INFO:tensorflow:loss = 1.0986121, step = 3100 (0.382 sec)
INFO:tensorflow:global_step/sec: 280.1
INFO:tensorflow:loss = 1.0986121, step = 3200 (0.357 sec)
INFO:tensorflow:global_step/sec: 280.162
INFO:tensorflow:loss = 1.0986121, step = 3300 (0.357 sec)
INFO:tensorflow:global_step/sec: 279.726
INFO:tensorflow:loss = 1.0986121, step = 3400 (0.358 sec)
INFO:tensorflow:global_step/sec: 256.025
INFO:tensorflow:loss = 1.0986121, step = 3500 (0.391 sec)
INFO:tensorflow:global_step/sec: 266.485
INFO:tensorflow:loss = 1.0986121, step = 3600 (0.375 sec)
INFO:tensorflow:global_step/sec: 284.511
INFO:tensorflow:loss = 1.0986121, step = 3700 (0.352 sec)
INFO:tensorflow:global_step/sec: 286.074
INFO:tensorflow:loss = 1.0986121, step = 3800 (0.349 sec)
INFO:tensorflow:global_step/sec: 254.908
INFO:tensorflow:loss = 1.0986121, step = 3900 (0.392 sec)
INFO:tensorflow:global_step/sec: 279.031
INFO:tensorflow:loss = 1.0986121, step = 4000 (0.358 sec)
INFO:tensorflow:global_step/sec: 260.814
INFO:tensorflow:loss = 1.0986121, step = 4100 (0.383 sec)
INFO:tensorflow:global_step/sec: 271.606
INFO:tensorflow:loss = 1.0986121, step = 4200 (0.368 sec)
INFO:tensorflow:global_step/sec: 267.028
INFO:tensorflow:loss = 1.0986121, step = 4300 (0.375 sec)
INFO:tensorflow:global_step/sec: 263.03
INFO:tensorflow:loss = 1.0986121, step = 4400 (0.380 sec)
INFO:tensorflow:global_step/sec: 277.83
INFO:tensorflow:loss = 1.0986121, step = 4500 (0.360 sec)
INFO:tensorflow:global_step/sec: 281.873
INFO:tensorflow:loss = 1.0986121, step = 4600 (0.355 sec)
INFO:tensorflow:global_step/sec: 282.674
INFO:tensorflow:loss = 1.0986121, step = 4700 (0.354 sec)
INFO:tensorflow:global_step/sec: 275.074
INFO:tensorflow:loss = 1.0986121, step = 4800 (0.364 sec)
INFO:tensorflow:global_step/sec: 278.626
INFO:tensorflow:loss = 1.0986121, step = 4900 (0.359 sec)
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 5000...
INFO:tensorflow:Saving checkpoints for 5000 into /var/folders/pt/1kfc9vl115q9sj4h8tff2q5c0000gn/T/tmpw1q7_ekt/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 5000...
INFO:tensorflow:Loss for final step: 1.0986121.

In [32]:
eval_result = classifier.evaluate(
    input_fn=lambda: input_fn(features,Labels, training=False))

print('\nTest set accuracy: {accuracy:0.3f}\n'.format(**eval_result))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2021-03-28T16:13:08Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/pt/1kfc9vl115q9sj4h8tff2q5c0000gn/T/tmpw1q7_ekt/model.ckpt-5000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 13.39662s
INFO:tensorflow:Finished evaluation at 2021-03-28-16:13:21
INFO:tensorflow:Saving dict for global step 5000: accuracy = 0.9041449, average_loss = 1.0986269, global_step = 5000, loss = 1.0986269
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 5000: /var/folders/pt/1kfc9vl115q9sj4h8tff2q5c0000gn/T/tmpw1q7_ekt/model.ckpt-5000

Test set accuracy: 0.904